### ISSUE TITLE
Ensure deployment records are up to date in the Lowell Probe Log

### ISSUE THREAD

**Issue by GMaynard1** [GMaynard1/emolt_project_management#18]
Email from Mike Morin on 12/22/2021

> I am seeing a lot of probes that are not even on the deployment sheet, thus not logged into our inventory.  I am also seeing missing or incomplete deployment records so I cannot accurately create the deployment in our system.

Huanxin, is there a file that's more up to date than [this one](https://docs.google.com/spreadsheets/d/1jWqLloD0PDBtUNKpzWBsnaXzOiYgdj_nOrGiGJwB8e0/edit#gid=1736128240)?

**Comment by xhx509** [comment]
We haven't updated that for a while. We keep our record in [telemetry_status](https://docs.google.com/spreadsheets/d/1CfEc4nstd04gg_rya8hFPEPt4Pe9iecp18GU0Pz931A/edit#gid=1507135250), column Q "logger change"

**Comment by GMaynard1** [comment]
Great, that's what I thought; I'd never even seen the sheet Mike was referencing. I'll get the updated info over to him. Thank you!

**Comment by jamespatrickmanning** [comment]
this is another issue that will probably be solved with new database system

**Comment by GMaynard1** [comment]
Up to date as of the end of July, need a process for keeping it that way...
