### ISSUE TITLE
Website Upgrade: Gear Types

### ISSUE THREAD

**Issue by GMaynard1** [GMaynard1/emolt_project_management#2]
**Is your feature request related to a problem? Please describe.**
@jamespatrickmanning and I were reviewing the lastfix website and realized it would be easier -- especially for people without all the vessels memorized (me) -- to identify potential problems with gear type (mobile or fixed) on lastfix.

**Describe the solution you'd like**
There should be a column on the lastfix website to describe whether a vessel is fixed or mobile gear

**Additional context**
Gear type changes the interpretation of fishing behavior. A mobile gear vessel should report new telemetry data every time it fishes. However, it is possible for a fixed gear vessel to report a fishing trip but not haul the gear that is rigged with an emolt system.

**Comment by xhx509** [comment]
Thanks for the comment, I will add a gear-type column first. and then add a function to check if there is a data transmission in one trip of fixed gear boat.

**Comment by jamespatrickmanning** [comment]
finished
