### ISSUE TITLE
[BUG:] emolt.dat is not sorted by time 

### ISSUE THREAD

**Issue by jamespatrickmanning** [GMaynard1/emolt_project_management#20]
### Bug Category

Data Processing

### Date Observed

2021-12-26

### Description

Shouldn't emolt.org/emoltdata/emolt.dat be sorted by time?  I noticed the "year" column has some "2020" after "2021".
The reason I noticed this is that I was expecting 2021 to have many more hauls than 2020 but it apparently has about 1000 less?
I'm wondering if there is a problem with the "year" column. We can talk about this in January 2022 but it should be top priority then.

### Potential Fix

Lets first make sure the year column is reported correctly?

**Comment by xhx509** [comment]
There are two boats Rolex and Charger with Rockblock+ have issues of the "year", they are ordered by the year-date. I am not sure how you count the hauls of each year, but it is possible that 2021 is less than 2020, Cause we have lots of Ap3 broken this year. I think we can compare 2021 vs 2020 by "emolt_QCed_telemetry_and_wified.csv", the raw data included.

**Comment by jamespatrickmanning** [comment]
Ok. Thanks.  I understand your 2nd and 3rd sentence. That makes sense.

However, I am not sure what you mean by the first sentence. "_There are two boats Rolex and Charger with Rockblock+ have issues of the "year", they are ordered by the year-date._"  We can talk about it next week.
