### ISSUE TITLE
Vessel visit GitHub Forms

### ISSUE THREAD

**Issue by GMaynard1** [GMaynard1/emolt_project_management#21]
### Suggestion Category

Miscellaneous

### Suggestion Description

Create a template for new vessel installations and / or cisits that can be filled out and store photos

Also check out [this code](https://github.com/wizaplace/github-to-mysql) to drag GitHub issues into MySQL to store records there in an easier to analyze way

**Comment by jamespatrickmanning** [comment]
Lets also discuss a **weekly routine** to document who is going to contact which fishermen and visit which dock.
Should we generate a shared calendar where we each record both plans and actual actions regarding vessel visits?  I just started a new google calendar and shared it with you.  There are three steps to a vessel visits: 1) arranging w/owner and/or captain, 2) actual visit, and 3) visit review.

Regarding a template for installations and visit reviews,  keep in mind there is a [googleform](https://docs.google.com/forms/d/e/1FAIpQLSeDjlwRoYqP4AFAK68NSBkIXLADvQaw68CY_wh_zynq1oLXtg/viewform)
 that Cassie created a few years back but, as we all agreed, we need to make a more efficient form that is already populates most fields after the user supplies the "vessel_name".

The challenge here is to keep things documented but, at the same time, minimize the paperwork required.

**Comment by GMaynard1** [comment]
Absolutely! I was thinking I'd put together a template that we could walk through with the Moragh K install to see if it captures everything we need. Capturing the info here will also provide a way for other people who were involved in the installation to contribute photos / comments (providing we can move the critical stuff over to MySQL easily enough).

**Comment by GMaynard1** [comment]
This is not the system we'll be using moving forward. Vessel visits need to tie in to the database for record keeping.
