### ISSUE TITLE
MySQL database Development

### ISSUE THREAD

**Issue by GMaynard1** [GMaynard1/emolt_project_management#43]
### Suggestion Category

Data Storage

### ERD is [here](https://app.diagrams.net/#HGMaynard1%2Femolt_project_management%2Fmain%2FeMOLT.drawio)

- Green tables have scripts below
- Red tables need to be drawn up and scripted
- White tables need to be scripted

- [x] [Contacts table to store info about eMOLT participants and support staff](https://github.com/GMaynard1/emolt_project_management/blob/main/Database_Builder/Create_Contacts.sql)
- [x] [Ports table based on FVTR.Ports, standardized with other NEFSC databases but including some eMOLT specific fields](https://github.com/GMaynard1/emolt_project_management/blob/main/Database_Builder/Create_Ports.sql)
- [x] [Programs table to track which type of eMOLT the vessel participates in](https://github.com/GMaynard1/emolt_project_management/blob/main/Database_Builder/Create_Programs.sql)
- [x] [Funding table to track how vessel equipment is funded](https://github.com/GMaynard1/emolt_project_management/blob/main/Database_Builder/Create_Funding.sql)
- [x] [Vessel table to track contact information, gear types, program affiliation, home port, etc.](https://github.com/GMaynard1/emolt_project_management/blob/main/Database_Builder/Create_Vessels.sql)
- [x] [Equipment inventory to track what eMOLT currently owns and maintains]()
- [x] [Vessel Program table to allow one vessel to participate in multiple programs](https://github.com/GMaynard1/emolt_project_management/blob/main/Database_Builder/Create_VesselPrograms.sql)
- [x] [Vessel Visit Log table](https://github.com/GMaynard1/emolt_project_management/blob/main/Database_Builder/Create_VisitLog.sql)
- [x] Equipment Change table to track probe and comm deployments
- [x] [Hardware address data to store MAC, Satellite, Bluetooth, etc. addresses](https://github.com/GMaynard1/emolt_project_management/blob/main/Database_Builder/Create_HardwareAddresses.sql)
- [x] [Gear code table similar to FVTR.FVTR_GEAR_CODES](https://github.com/GMaynard1/emolt_project_management/blob/main/Database_Builder/Create_GearCodes.sql) 

Raw data storage tasks TBD

**Comment by GMaynard1** [comment]
@Friskfisk we should talk about raw sensor data storage since I know you guys are working on a MySQL database and there's an existing (clunky) Oracle architecture at the NEFSC for Study Fleet participants. There's also a set of Oracle tables for @jamespatrickmanning 's traditional eMOLT vessels (non-realtime). I'd like to fold all of those efforts into one place if possible to minimize wheel reinvention.

**Comment by Friskfisk** [comment]
Sounds great, I agree and I'm all for discussing in detail. I added it to the next Wednesday call agenda G doc, if that works for you for a first crack at seeing where we want to go with this?
