### ISSUE TITLE
weekly operations w/dockside techs

### ISSUE THREAD

**Issue by GMaynard1** [GMaynard1/emolt_project_management#45]

**Comment by GMaynard1** [comment]
@jamespatrickmanning do you think it's worth creating an issue template (similar to the ones we already have) that provides a standardized way to assign tasks at the beginning of a week and track progress?

**Comment by jamespatrickmanning** [comment]
After Erin and I had a virtual meeting with Gio a few weeks ago,  he started a [googlesheet](https://docs.google.com/spreadsheets/d/1cHVS_B9AhbiFwnaR2LC959oGROOapRvSB-b-MqH5Xq0/edit#gid=0) that gets updated each week when dockside techs know their schedule.  The idea is that both eMOLT and SF techs fill this out and, in the future, we might also ask other organizations (CFRF, CCS, and NEMM, for example) to join us in this effort.  Lets talk about this some more.  We want to minimize the number of  documents and spreadsheets that dockside techs need to keep up-to-date.

**Comment by GMaynard1** [comment]
That's great! I've requested access and will take a look when Gio grants it off to me

**Comment by GMaynard1** [comment]
So, looking at this, it's fine for the moment, but I think we'll want to make the vessel names selectable from a list so that they are standardized (no abbreviations) and only one per line to make it easier to look at vessel visit history

**Comment by jamespatrickmanning** [comment]
Ok.  Gio's spreadsheet on who is visiting when is somewhat helpful but many dockside techs are not sure of their travels until the actual morning they are leaving.  The emails going out are more helpful so I will ask Huanxin to send an email (like the SF techs) when he is headed to a dock (especially if there is a SF vessel nearby).  Also, to help on this front, I added a few tabs to telemetry status listing/sorting boats respectively by "dockside_techs" and "region".

**Comment by jamespatrickmanning** [comment]
This item is related to the Monday and Thursday calls that I have been having with Huanxin where he is charged with writing down his "report" and "plan".   In addition to entering bullets in the agenda/minutes page, he is expected to modify Gio's Weekly Vessel Visits page.
