### ISSUE TITLE
F/V Ryan Joseph binary file parsing

### ISSUE THREAD

**Issue by jamespatrickmanning** [GMaynard1/emolt_project_management#65]

**Comment by jamespatrickmanning** [comment]
Has the parsing binary Moana file issue .. as reported by Cap Joe in a screen shot

**Comment by GMaynard1** [comment]
@xhx509 this is all squared away, right? he's got the logger and we just need to reinstall the deckbox?

**Comment by xhx509** [comment]
Yes, we need to reinstall the deckbox.
