### ISSUE TITLE
Mister_G flip screen

### ISSUE THREAD

**Issue by jamespatrickmanning** [GMaynard1/emolt_project_management#67]

**Comment by jamespatrickmanning** [comment]
- [ ] flip screen (can this be done via DWS?)
- [ ] pick up Lowell system power cord that JiM left behind

**Comment by xhx509** [comment]
Yes, we can flip the screen by DWS.

**Comment by GMaynard1** [comment]
Screen flipped on Wednesday 2022-08-17
