### ISSUE TITLE
Proud Mary recover probe

### ISSUE THREAD

**Issue by jamespatrickmanning** [GMaynard1/emolt_project_management#69]

**Comment by jamespatrickmanning** [comment]
- [ ] keep bugging Capt Chris to get the probe out of storage
- [ ] discuss Notis Trawlmaster installation progress and possibility of experimenting with that in the future

**Comment by GMaynard1** [comment]
Probe recovered on 2022-08-17

**Comment by jamespatrickmanning** [comment]
Erin took the probe home to Maine.
JiM has notes on Notus in an old  googledoc but he will start a new "issue" on this topic of Notus.
