### ISSUE TITLE
F/V Christi Caroline Rockblock messages

### ISSUE THREAD

**Issue by GMaynard1** [GMaynard1/emolt_project_management#83]
Messages coming in from the Christi Caroline are very frequent (43 transmissions since being powered on on Saturday night, 8/27/22) and formatted incorrectly for their current endpoint on the API. Each record appears to have been processed twice on acceptance by the API and currently reports the vessel fishing southwest of Sardinia in the Mediterranean Sea. @xhx509 should this vessel be transmitting to "old format, mobile gear" or "new format"? 

![Image](https://user-images.githubusercontent.com/77748586/187208527-07f6f4e1-34c5-4705-8b93-b446727bf370.PNG)

**Comment by xhx509** [comment]
Hi George
I am working on that.  CC is in "New format". The Moana logger SN is 0132.

**Comment by GMaynard1** [comment]
cool, thanks, I switched the CC over to the "new format" delivery group and will try to reload this weekends transmissions

**Comment by xhx509** [comment]
If you saw the letter "u" at the end of the data payload, it is in "new
format".  If it was "t", the data is in "old format" and is Lowell logger
data.

**Comment by GMaynard1** [comment]
All of these transmissions were able to go through the API when manually pushed back in.
