### ISSUE TITLE
[No payload] messages from Rockblocks

### ISSUE THREAD

**Issue by GMaynard1** [GMaynard1/emolt_project_management#91]
Some Rockblocks periodically send blank messages to the API. I'm not sure why this happens or if it matters. Most appear to come from the Christi Caroline and the Charger

![Image](https://user-images.githubusercontent.com/77748586/191041300-89755954-e721-4bee-a44b-592404a8eed2.PNG)

**Comment by xhx509** [comment]
No worries,  The satellite got "Check" signal(to notice satellite I will do something), but did not get the "data" signal. Usually cause by obstacle, such as wheelhouse.  We had similar issues on Ap3 before.

**Comment by xhx509** [comment]
If  satellite cannot get "Check" signal. You will get nothing on the site. In that case,  If you run codes manually in Raspberry Pi, you will see "transmit failed " at the end.

**Comment by GMaynard1** [comment]
Great, thanks!
